# datos nuevos

In [ ]:
!wget = 'https://storage.googleapis.com/datathon2022/labels_dataset1_v2.csv'

--2022-10-22 23:23:40--  http://=/
Resolving = (=)... failed: Name or service not known.
wget: unable to resolve host address ‘=’
--2022-10-22 23:23:40--  https://storage.googleapis.com/datathon2022/labels_dataset1_v2.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.127.128, 172.217.218.128, 142.250.153.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.127.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 482891 (472K) [text/csv]
Saving to: ‘labels_dataset1_v2.csv’

labels_dataset1_v2. 100%[===================>] 471.57K  --.-KB/s    in 0.004s  

2022-10-22 23:23:40 (113 MB/s) - ‘labels_dataset1_v2.csv’ saved [482891/482891]

FINISHED --2022-10-22 23:23:40--
Total wall clock time: 0.1s
Downloaded: 1 files, 472K in 0.004s (113 MB/s)


In [ ]:
import pandas as pd
df = pd.read_csv('labels_dataset1_v2.csv')
df.shape

(5459, 5)

# otros datos

In [ ]:
!wget 'https://storage.googleapis.com/datathon2022/dataset1_all_ogg.zip'

--2022-10-22 23:23:41--  https://storage.googleapis.com/datathon2022/dataset1_all_ogg.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.127.128, 172.217.218.128, 142.250.153.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.127.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3062626606 (2.9G) [application/zip]
Saving to: ‘dataset1_all_ogg.zip’

dataset1_all_ogg.zi 100%[===================>]   2.85G   247MB/s    in 12s     

2022-10-22 23:23:54 (235 MB/s) - ‘dataset1_all_ogg.zip’ saved [3062626606/3062626606]



In [ ]:
import zipfile

# Unzip the dataset
local_zip = 'dataset1_all_ogg.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('./')
zip_ref.close()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
file_name='datathon2022/dataset1/8937ed458beb41a5116dbd1857ff5d81.ogg'

In [ ]:
import IPython.display as ipd
import librosa
import librosa.display

In [1]:
plt.figure(figsize=(14,5))
data, sample_rate = librosa.load(file_name, sr=None) # al pasar el audio lo convierte en mono y normaliza wave default sr=22050
#librosa.display.waveplot(data, sr=sample_rate)
#ipd.Audio(file_name)

NameError: ignored

In [ ]:
# hertz, librosa convierte el audio a 22k predeterminadamente
sample_rate

50000

In [ ]:
# wave normalizado en 1 y -1 autom'aticamente por librosa
data

array([-4.3278265e-05,  5.9518225e-05,  1.4067440e-04, ...,
       -1.5423124e-04, -3.4798993e-04, -6.9866574e-04], dtype=float32)

# MFCC 
ver MEL y variantes de MFCC

In [ ]:
mfccs = librosa.feature.mfcc(y=data, sr=sample_rate, n_mfcc = 40)
mfccs.shape

(40, 28711)

In [ ]:
import os

audio_dataset = 'datathon2022/dataset1'
metadata = pd.read_csv('labels_dataset1_v2.csv')
metadata.head()

path    start  duration      end  \
0  012213d40662f86e8f775379bbf94dec   61.186     2.500   63.686   
1  0159af9f3ca04ada46f0c353ac210bb8   76.260    17.000   93.260   
2  0159af9f3ca04ada46f0c353ac210bb8  161.482     1.000  162.482   
3  0271a0818427d7fae7afde67bf49ba30   91.563     1.000   92.563   
4  0271a0818427d7fae7afde67bf49ba30  125.627     1.316  126.943   

               label  
0            whistle  
1  cetaceans_allfreq  
2              click  
3              click  
4              click

In [ ]:
metadata['label'].value_counts()

whistle              2879
click                2077
cetaceans_allfreq     476
allfreq                23
volcano                 4
Name: label, dtype: int64

In [ ]:
import numpy as np

In [ ]:
audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
mfccs_scaled_features

array([-6.1240131e+02,  6.2713078e+01,  1.2299292e+01,  1.4206262e+01,
        1.1232679e+01,  1.9311844e+01,  9.0929747e+00,  1.6953232e+01,
        9.1427523e-01,  1.5756428e+01, -1.4595189e+00,  1.7494476e+01,
        2.0122115e-01,  1.5999109e+01, -7.1178395e-01,  1.1250869e+01,
        4.8802072e-01,  8.3463602e+00,  3.3223779e+00,  4.3708754e+00,
        4.7990127e+00,  1.3982619e+00,  6.5874515e+00, -3.7823692e-01,
        6.7530923e+00, -1.2135158e+00,  5.6622930e+00, -1.2942307e+00,
        3.7180026e+00, -4.0419477e-01,  1.9675505e+00,  9.2695165e-01,
        2.9107392e-01,  1.7032784e+00, -9.3694806e-01,  2.1256697e+00,
       -1.0193832e+00,  2.3545506e+00, -3.7787488e-01,  1.8697883e+00],
      dtype=float32)

In [ ]:
metadata.loc[42]

path        035195366b6849c1b339cff8e6de574a
start                                101.438
duration                                 1.2
end                                  102.638
label                                whistle
Name: 42, dtype: object

In [ ]:
metadata.loc[42]['end']

102.63799999999992

In [ ]:
metadata.shape

(5459, 5)

# ejecutar

In [ ]:
def features_extractor(file):
  global audio
  global sample_rate
  if all(audio) != all(audio) or 1==1:
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
    start = int(str(round(row["start"],3)).replace('.',''))
    end =  int(str(round(row["end"],3)).replace('.',''))
    if end == 2940:
      end = 293944
    print (start)
    print(end)
    audio_trim, _ = librosa.effects.trim(audio[start:end])
    mfccs_features = librosa.feature.mfcc(y=audio_trim, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    return mfccs_scaled_features
  else:
    start = int(str(round(row["start"],3)).replace('.',''))
    end =  int(str(round(row["end"],3)).replace('.',''))
    if end == 2940:
      end = 293944
    print (start)
    print(end)
    audio_trim, _ = librosa.effects.trim(audio[start:end])
    mfccs_features = librosa.feature.mfcc(y=audio_trim, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    return mfccs_scaled_features

In [ ]:
import numpy as np
from tqdm import tqdm # progress meters in iterations
### Now we iterate through every audio file and extract features 
### using Mel-Frequency Cepstral Coefficients
extracted_features=[]
for index_num,row in tqdm(metadata.iterrows()):
    file_name = os.path.join(os.path.abspath(audio_dataset),str(row["path"])+str('.ogg'))
    final_class_labels=row["label"]
    data=features_extractor(file_name)
    extracted_features.append([data,final_class_labels])

1it [00:03,  3.50s/it]

61186
63686


2it [00:08,  4.59s/it]

7626
9326


3it [00:12,  4.10s/it]

161482
162482


4it [00:15,  3.87s/it]

91563
92563


5it [00:19,  3.72s/it]

125627
126943


6it [00:22,  3.64s/it]

135325
136325


6it [00:26,  4.38s/it]


KeyboardInterrupt: ignored

In [ ]:
### converting extracted_features to Pandas dataframe
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head() 

feature              class
0  [-669.2838, 53.59604, 13.355467, 22.64079, 14....            whistle
1  [-574.8974, 60.93311, -22.504108, 11.389624, -...  cetaceans_allfreq
2  [-568.7135, 62.4645, -17.676495, 17.210007, -0...              click
3  [-644.16644, 68.14601, 29.90164, 41.38941, 28....              click
4  [-644.51373, 64.669266, 20.134146, 32.405018, ...              click

In [ ]:
## datos almacenados
np.save('datathon2.npy', extracted_features)
extracted_features_df.to_csv('datathon2.csv')

/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


In [ ]:
ex = extracted_features[:]
exdf = extracted_features_df[:]

In [ ]:
ex

[[array([-6.69283813e+02,  5.35960388e+01,  1.33554668e+01,  2.26407909e+01,
          1.41457520e+01,  3.41034164e+01,  7.21812582e+00,  2.58764400e+01,
         -5.61121655e+00,  2.58834419e+01, -4.37880039e+00,  2.68563194e+01,
         -6.75238323e+00,  2.20093040e+01, -8.72427845e+00,  1.48810625e+01,
         -7.90528631e+00,  1.33094959e+01, -3.16732073e+00,  8.77440643e+00,
         -2.16545630e+00,  4.47995329e+00, -2.23361754e+00,  2.27937770e+00,
          1.87724662e+00, -2.22223997e+00, -1.29707620e-01, -4.24146980e-01,
          1.00275171e+00,  6.65427446e-01, -2.94696355e+00,  1.77922845e+00,
         -3.04017735e+00,  2.38299513e+00, -3.85519099e+00,  5.35812473e+00,
         -4.83932877e+00,  3.67013311e+00, -9.51417565e-01,  7.53256369e+00],
        dtype=float32), 'whistle'],
 [array([-574.8974    ,   60.93311   ,  -22.504108  ,   11.389624  ,
           -6.9385056 ,   20.168028  ,  -10.6017275 ,   18.179134  ,
          -11.534887  ,   17.637714  ,   -8.011074  ,  

In [ ]:
exdf

feature              class
0  [-669.2838, 53.59604, 13.355467, 22.64079, 14....            whistle
1  [-574.8974, 60.93311, -22.504108, 11.389624, -...  cetaceans_allfreq
2  [-568.7135, 62.4645, -17.676495, 17.210007, -0...              click
3  [-644.16644, 68.14601, 29.90164, 41.38941, 28....              click
4  [-644.51373, 64.669266, 20.134146, 32.405018, ...              click
5  [-639.2128, 61.402237, 15.381675, 29.429441, 1...              click

In [ ]:
# carcar datos
extracted_features = np.load('datathon2.npy', allow_pickle=True)

extracted_features_df = pd.read_csv('datathon2.csv')
extracted_features_df = extracted_features_df.drop('Unnamed: 0',1)
extracted_features_df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """


feature              class
0  [-6.69283813e+02  5.35960388e+01  1.33554668e+...            whistle
1  [-574.8974       60.93311     -22.504108     1...  cetaceans_allfreq
2  [-5.6871350e+02  6.2464500e+01 -1.7676495e+01 ...              click
3  [-6.4416644e+02  6.8146011e+01  2.9901640e+01 ...              click
4  [-6.4451373e+02  6.4669266e+01  2.0134146e+01 ...              click
5  [-6.39212830e+02  6.14022369e+01  1.53816748e+...              click

In [ ]:
ls

dataset1_all_ogg.zip  datathon2.csv  labels_dataset1_v2.csv
datathon2022/         datathon2.npy  sample_data/


In [2]:
da, _ = librosa.effects.trim(data[0:18])
#librosa.display.waveplot(da, sr=sample_rate)
#ipd.Audio(file_name) # todo el audio

NameError: ignored

In [ ]:
extracted_features

array([[array([-6.69283813e+02,  5.35960388e+01,  1.33554668e+01,  2.26407909e+01,
                1.41457520e+01,  3.41034164e+01,  7.21812582e+00,  2.58764400e+01,
               -5.61121655e+00,  2.58834419e+01, -4.37880039e+00,  2.68563194e+01,
               -6.75238323e+00,  2.20093040e+01, -8.72427845e+00,  1.48810625e+01,
               -7.90528631e+00,  1.33094959e+01, -3.16732073e+00,  8.77440643e+00,
               -2.16545630e+00,  4.47995329e+00, -2.23361754e+00,  2.27937770e+00,
                1.87724662e+00, -2.22223997e+00, -1.29707620e-01, -4.24146980e-01,
                1.00275171e+00,  6.65427446e-01, -2.94696355e+00,  1.77922845e+00,
               -3.04017735e+00,  2.38299513e+00, -3.85519099e+00,  5.35812473e+00,
               -4.83932877e+00,  3.67013311e+00, -9.51417565e-01,  7.53256369e+00],
              dtype=float32)                                                       ,
        'whistle'],
       [array([-574.8974    ,   60.93311   ,  -22.504108  ,   11

In [ ]:
type(extracted_features)

numpy.ndarray

In [ ]:
extracted_features.shape, extracted_features_df.shape

((6, 2), (6, 2))

# seccion en proceso

In [ ]:
### converting extracted_features to Pandas dataframe
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head()

feature              class
0  [-669.2838, 53.59604, 13.355467, 22.64079, 14....            whistle
1  [-574.8974, 60.93311, -22.504108, 11.389624, -...  cetaceans_allfreq
2  [-568.7135, 62.4645, -17.676495, 17.210007, -0...              click
3  [-644.16644, 68.14601, 29.90164, 41.38941, 28....              click
4  [-644.51373, 64.669266, 20.134146, 32.405018, ...              click

In [ ]:
extracted_features_df.shape

(6, 2)

In [ ]:
### Split the dataset into independent and dependent dataset
X=np.array(extracted_features_df['feature'].tolist())
y=np.array(extracted_features_df['class'].tolist())

In [ ]:
X[0]

array([-6.69283813e+02,  5.35960388e+01,  1.33554668e+01,  2.26407909e+01,
        1.41457520e+01,  3.41034164e+01,  7.21812582e+00,  2.58764400e+01,
       -5.61121655e+00,  2.58834419e+01, -4.37880039e+00,  2.68563194e+01,
       -6.75238323e+00,  2.20093040e+01, -8.72427845e+00,  1.48810625e+01,
       -7.90528631e+00,  1.33094959e+01, -3.16732073e+00,  8.77440643e+00,
       -2.16545630e+00,  4.47995329e+00, -2.23361754e+00,  2.27937770e+00,
        1.87724662e+00, -2.22223997e+00, -1.29707620e-01, -4.24146980e-01,
        1.00275171e+00,  6.65427446e-01, -2.94696355e+00,  1.77922845e+00,
       -3.04017735e+00,  2.38299513e+00, -3.85519099e+00,  5.35812473e+00,
       -4.83932877e+00,  3.67013311e+00, -9.51417565e-01,  7.53256369e+00],
      dtype=float32)

In [ ]:
X.shape

(6, 40)

In [ ]:
y

array(['whistle', 'cetaceans_allfreq', 'click', 'click', 'click', 'click'],
      dtype='<U17')

In [ ]:
### Label Encoding
###y=np.array(pd.get_dummies(y))
### Label Encoder
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))


In [ ]:
y

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [ ]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
X_train

array([[-5.74897400e+02,  6.09331093e+01, -2.25041084e+01,
         1.13896236e+01, -6.93850565e+00,  2.01680279e+01,
        -1.06017275e+01,  1.81791344e+01, -1.15348873e+01,
         1.76377144e+01, -8.01107407e+00,  2.45871353e+01,
        -2.49801111e+00,  2.22035561e+01, -5.46468306e+00,
         1.59278498e+01, -3.99568009e+00,  8.68240547e+00,
        -4.66794968e+00,  9.37752151e+00,  6.91066742e-01,
         6.78508615e+00, -5.75744629e+00,  5.39815569e+00,
         4.34647560e+00,  6.26887941e+00, -1.45134997e+00,
         3.00728178e+00, -1.49428225e+00,  7.48325634e+00,
        -2.57521176e+00,  4.28094101e+00, -1.45446944e+00,
         8.01363564e+00, -1.56243622e+00,  5.33840656e+00,
        -4.71620321e+00,  2.96134305e+00, -4.51803446e+00,
         2.64782500e+00],
       [-6.44166443e+02,  6.81460114e+01,  2.99016399e+01,
         4.13894081e+01,  2.88228264e+01,  2.43113060e+01,
        -4.36631775e+00,  2.19168243e+01,  3.44001842e+00,
         1.12989540e+01, -1.03

In [ ]:
y

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [ ]:
X_train.shape

(4, 40)

In [ ]:
X_test.shape

(2, 40)

In [ ]:
y_train.shape

(4, 3)

In [ ]:
y_test.shape

(2, 3)

# Model Creation 1

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [ ]:
### No of classes
num_labels=y.shape[1]

In [ ]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [ ]:
# edit model

model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(400))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###four layer
model.add(Dense(300))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###five layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###six layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               4100      
                                                                 
 activation (Activation)     (None, 100)               0         
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 200)               20200     
                                                                 
 activation_1 (Activation)   (None, 200)               0         
                                                                 
 dropout_1 (Dropout)         (None, 200)               0         
                                                                 
 dense_2 (Dense)             (None, 100)               2

In [ ]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [ ]:
## Trianing my model
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 

num_epochs = 100
num_batch_size = 32

checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.hdf5', 
                               verbose=1, save_best_only=True)
start = datetime.now()

model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

In [ ]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.5


In [ ]:
mm = model.predict(X_test)
mm.shape

1/1 [==============================] - 0s 79ms/step


(2, 3)

### Testing Some Test Audio Data

Steps
- Preprocess the new audio data
- predict the classes
- Invere transform your Predicted Label

# predict basico

In [ ]:
filename="datathon2022/dataset1/837d2f6c7a0a5a12f78c3c7770d9329d.ogg"
prediction_feature=features_extractor(filename)
prediction_feature=prediction_feature.reshape(1,-1)
predicted_label = np.argmax((model.predict(prediction_feature) > 0.5).astype("int32"))
predicted_label

In [ ]:
metadata['label'].unique()

array(['whistle', 'cetaceans_allfreq', 'click', 'volcano', 'allfreq'],
      dtype=object)

In [ ]:
metadata.loc[metadata['label'] == 'allfreq']

# predict hecho para varios datos

In [ ]:
#varios datos
dato = metadata[4850:4900]
dato

In [ ]:
def features_extractor_b(file):
  global audio
  global sample_rate
  if all(audio) == all(audio) or 1 == 1:
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
    start = int(str(round(row["start"],3)).replace('.',''))
    end =  int(str(round(row["end"],3)).replace('.',''))
    if end == 2940:
      end = 293944
    print (start)
    print(end)
    audio_trim, _ = librosa.effects.trim(audio[start:end])
    mfccs_features = librosa.feature.mfcc(y=audio_trim, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    return mfccs_scaled_features
  else:
    start = int(str(round(row["start"],3)).replace('.',''))
    end =  int(str(round(row["end"],3)).replace('.',''))
    if end == 2940:
      end = 293944
    print (start)
    print(end)
    audio_trim, _ = librosa.effects.trim(audio[start:end])
    mfccs_features = librosa.feature.mfcc(y=audio_trim, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    return mfccs_scaled_features

In [ ]:
extracted_features_b = []

for index_num,row in tqdm(dato.iterrows()):
    file_name = os.path.join(os.path.abspath(audio_dataset),str(row["path"])+str('.ogg'))
    final_class_labels=row["label"]
    data=features_extractor_b(file_name)
    extracted_features_b.append([data,final_class_labels])

In [ ]:
extracted_features_b[9][0]

In [ ]:
# multiples datos hasta aqui
jajant = []

for i in range(0,50):
  print(np.argmax((model.predict(extracted_features_b[i][0].reshape(1,-1)) > 0.5).astype("int32")))
  jajant.append(np.argmax((model.predict(extracted_features_b[i][0].reshape(1,-1)) > 0.5).astype("int32")))
  print(jajant)

# predict hecho para un dato

In [ ]:
# un solo dato
dato = metadata.iloc[34].to_frame().T
dato

path start duration    end  label
160  083edafa2b1d1f1944018ca7d2e28e97   0.0    294.0  294.0  click

In [ ]:
prediction_feature=extracted_features_b[0][0]
prediction_feature=prediction_feature.reshape(1,-1)
predicted_label = np.argmax((model.predict(prediction_feature) > 0.5).astype("int32"))
predicted_label

1/1 [==============================] - 0s 17ms/step


4

In [ ]:
predicted_label = np.array(predicted_label)
predicted_label = predicted_label.reshape(1,-1)
labelencoder.inverse_transform(predicted_label)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:154: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['whistle'], dtype='<U17')

In [ ]:
labelencoder.__dict__

{'classes_': array(['allfreq', 'cetaceans_allfreq', 'click', 'volcano', 'whistle'],
       dtype='<U17')}

In [ ]:
dd = np.round_(model.predict(prediction_feature), decimals = 3)
dd

1/1 [==============================] - 0s 25ms/step


array([[0.012, 0.169, 0.002, 0.002, 0.814]], dtype=float32)

In [ ]:
metadata['label'].unique()

array(['click', 'whistle', 'cetaceans_allfreq', 'volcano', 'allfreq'],
      dtype=object)

# predict cofusion matrix

In [ ]:
# varios datos
ypred = model.predict(X_test)
ypred.shape, y_test.shape

1/1 [==============================] - 0s 19ms/step


((2, 3), (2, 3))

In [ ]:
y_pred = np.round_(ypred, decimals = 0)
y_pred

array([[0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
y_test

array([[0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [ ]:
y_pred[0]

array([0., 1., 0.], dtype=float32)

In [ ]:
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix
y_true = y_test
y_pred = y_pred
confusion_matrix = multilabel_confusion_matrix(y_true, y_pred)
confusion_matrix

array([[[2, 0],
        [0, 0]],

       [[0, 0],
        [1, 1]],

       [[1, 1],
        [0, 0]]])

In [ ]:
y_p = y_pred.argmax(axis=1)
y_t = y_test.argmax(axis=1)

In [ ]:
labels = ['allfreq', 'cetaceans_allfreq', 'click', 'volcano', 'whistle']
labels

['allfreq', 'cetaceans_allfreq', 'click', 'volcano', 'whistle']

In [ ]:
y_true = y_t
y_pred = y_p

In [3]:
'''
# graphic 0 with sklearn ConfusionMatrixDsplay and plt
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics



confusion_matrix = metrics.confusion_matrix(y_true, y_pred)

cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels =labels)
cm_display.plot()

plt.show()
'''

'\n# graphic 0 with sklearn ConfusionMatrixDsplay and plt\nimport matplotlib.pyplot as plt\nimport numpy as np\nfrom sklearn import metrics\n\n\n\nconfusion_matrix = metrics.confusion_matrix(y_true, y_pred)\n\ncm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels =labels)\ncm_display.plot()\n\nplt.show()\n'

In [4]:
'''
# graphic 1 with pretty_confusion_matrix
!pip install pretty_confusion_matrix
from pretty_confusion_matrix import pp_matrix_from_data

cmap = 'PuRd'
pp_matrix_from_data(y_true, y_pred)
'''

"\n# graphic 1 with pretty_confusion_matrix\n!pip install pretty_confusion_matrix\nfrom pretty_confusion_matrix import pp_matrix_from_data\n\ncmap = 'PuRd'\npp_matrix_from_data(y_true, y_pred)\n"

In [ ]:
# clases multiples
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics as mt

  # genera la matriz en texto
print(mt.confusion_matrix(y_true, y_pred))

  # muestra los diversos valores de esta, ''cualquiera cerca a uno mejor''
      #print accuracy of model
print('Accuracy: ',mt.accuracy_score(y_true, y_pred))
      #print precision value of model
print('Precision: ',mt.precision_score(y_true, y_pred,average='micro'))
      #print recall value of model
print('Recall: ',mt.recall_score(y_true, y_pred,average='micro')) # recall no tiene que ser mayor a accuracy y precision
      # print de f1-score
print('F1: ',mt.f1_score(y_true,y_pred,average='micro'))

# plot
confusion_matrix = mt.confusion_matrix(y_true, y_pred)
cm_display = mt.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels =labels) # display_labels = None
cm_display.plot()
fig = cm_display.ax_.get_figure() 
fig.set_figwidth(10)
fig.set_figheight(10) 
plt.show()

In [ ]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.5


# revisar

# evaluacion

In [ ]:
!pip install sed_eval

In [ ]:
from sed_eval.sound_event import SegmentBaseMetrics
base = SegmentBasedMetrics.results()

In [ ]:
import sed_eval

In [ ]:
sed_eval.sound_event.SegmentBasedMetrics.evaluate

<function sed_eval.sound_event.SegmentBasedMetrics.evaluate(self, reference_event_list, estimated_event_list, evaluated_length_seconds=None)>

In [ ]:
# Create metrics classes, define parameters
segment_based_metrics = sed_eval.sound_event.SegmentBasedMetrics(
    event_label_list=event_labels,
    time_resolution=1.0
)

event_based_metrics = sed_eval.sound_event.EventBasedMetrics(
    event_label_list=event_labels,
    t_collar=0.250
)

# Go through files
for file_pair in data:
    segment_based_metrics.evaluate(
        reference_event_list=file_pair['reference_event_list'],
        estimated_event_list=file_pair['estimated_event_list']
    )

    event_based_metrics.evaluate(
        reference_event_list=file_pair['reference_event_list'],
        estimated_event_list=file_pair['estimated_event_list']
    )

# Get only certain metrics
overall_segment_based_metrics = segment_based_metrics.results_overall_metrics()
print("Accuracy:", overall_segment_based_metrics['accuracy']['accuracy'])

# Or print all metrics as reports
print(segment_based_metrics)
print(event_based_metrics)

NameError: ignored

#segundo modelo

In [ ]:
X_train[0].shape

(40,)

In [ ]:
y_train

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
model.add(Dense(100,input_shape=(40,)))

In [ ]:
#eeeeeeeeeeeeeeeeeeeeeeeeeeeeee
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [ ]:
from tensorflow.python.ops.nn_ops import dropout
# Define the model
model = tf.keras.models.Sequential([

  tf.keras.layers.Dense(100, input_shape=(40,)),
  tf.keras.layers.Dense(200, activation=tf.nn.relu),
#  tf.keras.layers.Dropout(.2, input_shape=(2,)),
  tf.keras.layers.Dense(100, activation=tf.nn.relu),
  tf.keras.layers.Dense(5, activation=tf.nn.softmax)
])

# Compile the model
model.compile(optimizer=tf.optimizers.Adam(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    '''
    Halts the training after reaching 60 percent accuracy

    Args:
      epoch (integer) - index of epoch (required but unused in the function definition below)
      logs (dict) - metric results from the training epoch
    '''

    # Check accuracy
    if(logs.get('loss') < 0.4 ):

      # Stop if threshold is met
      print("\nLoss is lower than 0.4 so cancelling training!")
      self.model.stop_training = True

# Instantiate class
callbacks = myCallback()

In [ ]:
# Train the model with a callback
num_epochs = 500
num_batch_size = 32
model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), verbose=1)

In [ ]:
model.summary()

In [ ]:
from tensorflow.keras.optimizers import RMSprop

model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# All images will be rescaled by 1./255
train_datagen = ImageDataGenerator(rescale=1/255)

# Flow training images in batches of 128 using train_datagen generator
train_generator = train_datagen.flow_from_directory(
        './horse-or-human/',  # This is the source directory for training images ## should be a relative path to the directory containing the data
        target_size=(300, 300),  # All images will be resized to 300x300 ## set this equal to the resolution of each image (excluding the color dimension)
        batch_size=128, # evita el ahogo de memoria al pasar los datos por lotes ##     # - batch_size: number of images the generator yields when asked for a next batch. Set this to 10.

        # Since we use binary_crossentropy loss, we need binary labels
        class_mode='binary') # porque usamos un clasificaci'on binaria? ## How the labels are represented. Should be one of "binary", "categorical" or "sparse".


In [ ]:
history = model.fit(
      train_generator,
      steps_per_epoch=8,  # evita errores con quedarse sin ram, al pasar los datos por lotes de 8 partes 
      epochs=15,
      verbose=1)

In [ ]:
model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)
